spring.application.name=justride

aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.region=us-east-1
aws.dynamodb.access-key=awsAccessKey
aws.dynamodb.secret-key=awsSecretKey
aws.dynamodb.table-name=Car